name:telegram-file-link-bot-blueprint

services:- type: web
    name: file-link-bot
    env: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    port:8080
    healthCheckPath: /
    plan: free
    autoDeploy: true
    envVars:
      - key: API_ID
        value: "YOUR_API_ID_HERE"

      - key: API_HASH
        value: "YOUR_API_HASH_HERE"

      - key: BOT_TOKEN
        value: "YOUR_BOT_TOKEN_HERE"

      - key: MONGO_URI
        value: "YOUR_MONGO_URI_HERE"

      - key: LOG_CHANNEL
        value: "YOUR_LOG_CHANNEL_ID"

      - key: UPDATE_CHANNEL
        value: "YOUR_UPDATE_CHANNEL_USERNAME_WITHOUT_@"

      - key: ADMIN_IDS
        value: "YOUR_ADMIN_IDS_COMMA_SEPARATED"
