services:
  - type: web
    name: telegram-file-link-bot
    env: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: API_ID
        value: "38557745"
      - key: API_HASH
        value: "095e7cb4ee689244d024db2094815845"
      - key: BOT_TOKEN
        value: "7551749323:AArchMb6k01lahR0qDP7xoRjGm5WlJFAzeg"
      - key: MONGO_URI
        value: "mongodb+srv://mdparvez:Parvez129@cluster0.eebggak.mongodb.net/?retryWrites=true&w=majority"
      - key: LOG_CHANNEL
        value: "1002272193586"
      - key: UPDATE_CHANNEL
        value: "Tobifube"
      - key: ADMIN_IDS
        value: "6902088646"
